# Generated by Django 4.0.5 on 2022-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/imagenes/')),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos1',
                'db_table': 'productos1',
                'ordering': ['id'],
            },
        ),
    ]
